name: check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
      - name: Check Nix formatting
        run: nix fmt -- --ci

  check:
    runs-on: ${{ matrix.os }}
    needs: format
    permissions:
      contents: read
      actions: write
    
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, ubuntu-24.04-arm, macos-latest ]

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - uses: nixbuild/nix-quick-install-action@9f63be77f412a248c9d9a65a4c82cf066cdf8f0c # v35
      - uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7.0.2
        with:
          primary-key: nix-${{ matrix.os }}-${{ hashFiles('flake.lock') }}
          restore-prefixes-first-match: nix-${{ matrix.os }}-
          purge: true
          purge-prefixes: nix-${{ matrix.os }}-
          purge-created: 0
      - name: Run nix flake check
        run: nix flake check --option keep-going true
