name: Update flake

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          persist-credentials: false

      - uses: nixbuild/nix-quick-install-action@5bb6a3b3abe66fd09bbf250dce8ada94f856a703 # v30

      - name: Update flake inputs
        id: update-flake
        run: |
          COMMIT_MESSAGE=$(nix flake update 2>&1 | grep -v "^warning:")
          
          # Save the filtered output for later use
          echo "commit_message<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        with:
          token: ${{ steps.app-token.outputs.token }}
          title: "flake.lock: Update"
          branch: update-flake
          commit-message: |
            flake.lock: Update

            ${{ steps.update-flake.outputs.commit_message }}
          sign-commits: true

      # - name: Enable auto-merge
      #   if: steps.create-pr.outputs.pull-request-number
      #   run: |
      #     gh pr merge --auto --merge "${{ steps.create-pr.outputs.pull-request-number }}"
      #   env:
      #     GH_TOKEN: ${{ steps.app-token.outputs.token }}

